### ISSUE TITLE
Taxonomy term (OAI Set) update error

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#234]
When updating a taxonomy term or deleting a taxonomy term in the "OAI Sets" vocab, there is an error that seems to have something to do with the search_api indexing.

**Comment by wgilling** [comment]
Stack trace of the error:
Error: Call to a member function getColumns() on boolean in Drupal\Core\Entity\Query\Sql\Tables->addField() (line 253 of /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Query/Sql/Tables.php)
```
#0 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Query/Sql/Condition.php(52): Drupal\Core\Entity\Query\Sql\Tables->addField('field_linked_ag...', 'INNER', NULL)
#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(172): Drupal\Core\Entity\Query\Sql\Condition->compile(Object(Drupal\Core\Database\Driver\mysql\Select))
#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(80): Drupal\Core\Entity\Query\Sql\Query->compile()
#3 /var/www/html/drupal/web/modules/contrib/search_api/src/Plugin/search_api/datasource/ContentEntity.php(1074): Drupal\Core\Entity\Query\Sql\Query->execute()
#4 /var/www/html/drupal/web/modules/contrib/search_api/src/Utility/TrackingHelper.php(123): Drupal\search_api\Plugin\search_api\datasource\ContentEntity->getAffectedItemsForEntityChange(Object(Drupal\taxonomy\Entity\Term), Array, NULL)
#5 /var/www/html/drupal/web/modules/contrib/search_api/search_api.module(255): Drupal\search_api\Utility\TrackingHelper->trackReferencedEntityUpdate(Object(Drupal\taxonomy\Entity\Term), true)
#6 [internal function]: search_api_entity_delete(Object(Drupal\taxonomy\Entity\Term))
#7 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('search_api_enti...', Array)
#8 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(206): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_delete', Array)
#9 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(843): Drupal\Core\Entity\EntityStorageBase->invokeHook('delete', Object(Drupal\taxonomy\Entity\Term))
#10 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(434): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('delete', Object(Drupal\taxonomy\Entity\Term))
#11 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(786): Drupal\Core\Entity\EntityStorageBase->delete(Array)
#12 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityBase.php(403): Drupal\Core\Entity\Sql\SqlContentEntityStorage->delete(Array)
#13 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityDeleteForm.php(73): Drupal\Core\Entity\EntityBase->delete()
#14 [internal function]: Drupal\Core\Entity\ContentEntityDeleteForm->submitForm(Array, Object(Drupal\Core\Form\FormState))
#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array(Array, Array)
#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState))
#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(593): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState))
#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm('taxonomy_term_o...', Array, Object(Drupal\Core\Form\FormState))
#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(91): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\taxonomy\Form\TermDeleteForm), Object(Drupal\Core\Form\FormState))
#20 /var/www/html/drupal/web/core/modules/layout_builder/src/Controller/LayoutBuilderHtmlEntityFormController.php(39): Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#21 [internal function]: Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#22 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#24 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#25 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#26 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#27 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#28 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /var/www/html/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#37 {main}
.
```

**Comment by elizoller** [comment]
patching core from https://www.drupal.org/project/drupal/issues/2893747
