### ISSUE TITLE
Views "view all" option WSOD

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#556]
If you select "All" when choosing the number of items to reorder in any complex object, it gives the following error message: "The website encountered  an unexpected error. Please try again later."

**Comment by seth-shaw-asu** [comment]
Error message from test in PRISM:
```
TypeError: Unsupported operand types: int * string in Drupal\views\Plugin\views\pager\SqlBase->query() (line 279 of /var/www/html/drupal/web/core/modules/views/src/Plugin/views/pager/SqlBase.php)
#0 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/query/Sql.php(1451): Drupal\views\Plugin\views\pager\SqlBase->query()
#1 /var/www/html/drupal/web/modules/contrib/group/group.module(280): Drupal\views\Plugin\views\query\Sql->build()
#2 [internal function]: group_views_query_alter()
#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array()
#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}()
#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#6 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/query/Sql.php(1433): Drupal\Core\Extension\ModuleHandler->invokeAll()
#7 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1316): Drupal\views\Plugin\views\query\Sql->alter()
#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/PathPluginBase.php(392): Drupal\views\ViewExecutable->build()
#9 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/Page.php(196): Drupal\views\Plugin\views\display\PathPluginBase->execute()
#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1630): Drupal\views\Plugin\views\display\Page->execute()
#11 /var/www/html/drupal/web/core/modules/views/src/Element/View.php(81): Drupal\views\ViewExecutable->executeDisplay()
#12 [internal function]: Drupal\views\Element\View::preRenderViewElement()
```

This appears to be a known issue with Drupal 9.x and PHP 8: https://www.drupal.org/project/drupal/issues/3266341.

**Comment by seth-shaw-asu** [comment]
Probably just need to add the patch to `composer.json` and test.

Ideally we would contribute test coverage so that it could get merged into the next version of Drupal, but it isn't clear where we would add the test, as that class doesn't appear to have an existing test to build on. 🤷‍♂️

**Comment by seth-shaw-asu** [comment]
Committed to composer.json: https://github.com/asulibraries/islandora-repo/commit/fa43e686970f5e027b24f8bee5e2f5073a414e5f but still need to be pushed to production.
